INSERT INTO USER_ROLES(ROLE_ID,ROLE_DESC,CREATED_BY,CREATED_DATE) values  (10,'GUEST','KRUPAHARAN',sysdate);
INSERT INTO USER_ROLES(ROLE_ID,ROLE_DESC,CREATED_BY,CREATED_DATE) values  (1,'ADMIN','AMITHABH',sysdate);

INSERT INTO USER_PROFILE(BEMS_ID,ROLE_ID,USER_NAME,EMAIL_ADDRESS,CREATED_BY,CREATED_DATE) values  (3029018,1,'AMITHABH','amitabh.rathore@boeing.com','SYSTEM',sysdate);
